Update template
DeNepo/template-html-css pull request #9
Opened 2023-10-26 22:04 UTC by talmurshidi

## Description

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

2023-10-27 13:50 UTC, colevandersWands requested changes

2023-10-27 13:50 UTC, colevandersWands commented on package.json
>    "author": "HYF Belgium",
change to DeNepo, since the license changed

2023-10-28 13:31 UTC, talmurshidi commented on package.json
>    "author": "HYF Belgium",
Done.

2023-10-30 12:01 UTC, colevandersWands approved these changes

2023-10-30 12:02 UTC, merged